/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {

    // @Test public void calculatorTest() {
    //     assertEquals(4, new Calculator(new Lexer("2 + 2")).expr());
    //     assertEquals(8, new Calculator(new Lexer("2 + 2 + 2 + 2 + 2 - 2")).expr());
    //     assertEquals(12, new Calculator(new Lexer("12 + 2 - 2")).expr());
    //     assertEquals(100, new Calculator(new Lexer("100 - 50 + 48+2")).expr());
    //     assertEquals(14, new Calculator(new Lexer("7 * 4 / 2")).expr());
    //     assertEquals(42, new Calculator(new Lexer("7 * 4 / 2 * 3")).expr());
    //     assertEquals(30, new Calculator(new Lexer("10 * 4  * 2 * 3 / 8")).expr());
    //     assertEquals(50, new Calculator(new Lexer("8 + 7 * 4 / 2 * 3")).expr());
    //     assertEquals(30, new Calculator(new Lexer("2 + 7 * 4")).expr());
    //     assertEquals(5, new Calculator(new Lexer("7 - 8 / 4")).expr());
    //     assertEquals(17, new Calculator(new Lexer("14 + 2 * 3 - 6 / 2")).expr());
    //     assertEquals(4, new Calculator(new Lexer("(2 + 2)")).expr());
    //     assertEquals(4, new Calculator(new Lexer("0 + (2 + 2)")).expr());
    //     assertEquals(7, new Calculator(new Lexer("12 - (2 * ((2 * 2))) + 3")).expr());
    // }
}
